export const LOGIN_USER = 'LOGIN_USER';
export const LOGOUT_USER = 'LOGOUT_USER';

export const LOAD_CHALLENGE = 'LOAD_CHALLENGE';
export const LOAD_CHALLENGES = 'LOAD_CHALLENGES';
export const COMPLETE_CHALLENGE = 'COMPLETE_CHALLENGE';
