# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-08 21:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0003_auto_20160908_1512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='cipher',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='known_cipher',
        ),
        migrations.AddField(
            model_name='challenge',
            name='description',
            field=models.CharField(default='', max_length=10000),
        ),
    ]
