# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-09 05:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('challenge', '0004_auto_20160908_1649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='completedchallenge',
            name='challenge',
        ),
        migrations.RemoveField(
            model_name='completedchallenge',
            name='user',
        ),
        migrations.AddField(
            model_name='challenge',
            name='users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='CompletedChallenge',
        ),
    ]
