# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-09 18:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0005_auto_20160909_0046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='path',
        ),
        migrations.DeleteModel(
            name='Path',
        ),
    ]
