# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-21 04:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0007_better_challenge_field_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='points',
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AddField(
            model_name='challenge',
            name='points_required',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
