# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-21 06:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cryptographer', '0001_cryptographer_user'),
        ('challenge', '0008_challenge_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompletedChallenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='users',
        ),
        migrations.AddField(
            model_name='completedchallenge',
            name='challenge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challenge.Challenge'),
        ),
        migrations.AddField(
            model_name='completedchallenge',
            name='cryptographer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cryptographer.Cryptographer'),
        ),
    ]
