# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-21 06:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptographer', '0001_cryptographer_user'),
        ('challenge', '0009_cryptographer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='users',
            field=models.ManyToManyField(blank=True, through='challenge.CompletedChallenge', to='cryptographer.Cryptographer'),
        ),
    ]
