# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-07 05:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0010_challenge_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='cipher',
            field=models.CharField(choices=[('SH', 'Shift'), ('VI', 'Vigenère'), ('UN', 'Unknown')], default='UN', max_length=2),
        ),
    ]
